Description: >
  Dimeji Oladepo / Cloud devops nanodegree capstone project
  Setup Jenkins
Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

Resources:
  JenkinsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow http and ssh on bastion instance"
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
        - CidrIp: "0.0.0.0/0"
          IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
        - CidrIp: "0.0.0.0/0"
          IpProtocol: "tcp"
          FromPort: 8080
          ToPort: 8080
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"

  BastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06ce3edf0cff21f07
      InstanceType: t2.medium
      KeyName: "Bastion"
      SecurityGroupIds:
        - Ref: JenkinsSecurityGroup
      SubnetId:
        Fn::ImportValue: !Sub ${EnvironmentName}-PUB1-SUBNETS
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update
          sudo yum install java-1.8.0-openjdk
          curl --silent --location http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo | sudo tee /etc/yum.repos.d/jenkins.repo
          sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
          sudo yum install jenkins -y
          sudo systemctl start jenkins
          sudo ufw allow 8080
          sudo amazon-linux-extras install epel
          sudo amazon-linux-extras install nginx1
          sudo systemctl start nginx
          sudo systemctl enable nginx
          sudo yum install tidy 
          curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
